FROM gcr.io/google-appengine/tomcat
#RUN mkdir $APP_DESTINATION_WAR
COPY ./godshivam-0.0.1-SNAPSHOT.war $APP_DESTINATION_WAR/root.war
#RUN $CATALINA_HOME/bin/startup.sh
#   && chown -R tomcat:tomcat $APP_DESTINATION_WAR


